name: build
on: [push, pull_request]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate test Report
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml --cov-config=.coveragerc
          pytest --cov=./ --cov-report=html --cov-config=.coveragerc
      - name: Upload Coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml,./coverage2.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
